import type { Metadata } from "next";
import localFont from "next/font/local";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import "./globals.css";
import { SocketProvider } from "@/context/SocketContext";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <SocketProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <div className="flex flex-col items-center justify-items-center w-full min-h-screen p-8 pb-20 gap-16 sm:p-20">
              {children}
            </div>
            <Toaster />
          </body>
        </html>
      </SocketProvider>
    </ClerkProvider>
  );
}
